name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'  # Needed for workload identity federation

    steps:
    - uses: actions/checkout@v4

    - name: Authenticate with GCP using Service Account Key
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}  

    - id: 'Build and Push Docker Image'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:${{ github.sha }}

    - id: 'SSH Deploy via IAP'
      uses: 'google-github-actions/ssh-compute@v1'
      with:
        instance_name: 'hobby-vm'
        zone: 'northamerica-northeast2-a'  # Replace with your VM zone
        project_id: '${{ secrets.GCP_PROJECT_ID }}'
        ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
        command: |
          cd /home/ubuntu/app
          docker-compose pull
          docker-compose up -d
